# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Owner/OneDrive/pic/Documents/GitHub/chasebot/camera/camera.srcs/sources_1/ip/divider32/divider32.xci
# IP: The module: 'divider32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Owner/OneDrive/pic/Documents/GitHub/chasebot/camera/camera.srcs/sources_1/ip/divider32/divider32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Owner/OneDrive/pic/Documents/GitHub/chasebot/camera/camera.srcs/sources_1/ip/divider32/divider32.xci
# IP: The module: 'divider32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Owner/OneDrive/pic/Documents/GitHub/chasebot/camera/camera.srcs/sources_1/ip/divider32/divider32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divider32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
