# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/ubuntu/6.111/camera/camera.srcs/sources_1/new/nexys4ddr.xdc

# IP: ip/sqrt/sqrt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sqrt || ORIG_REF_NAME==sqrt} -quiet] -quiet
